### ISSUE TITLE
Feature Request: Customizable Region Marker

### ISSUE THREAD

**Issue by jplehmann** [Quorafind/Obsidian-Fold-Anywhere#11]
### Feature Requested

As a VIM user, I use arbitrary manual folds extensively, which this plugin helps me accomplish in Obsidian. I have found no other way.  Thank you!

Could it be possible to customize the fold markers, which are currently `%% REGION %%`?  In particular, I'd like it to support [VIM's default fold markers](https://vimdoc.sourceforge.net/htmldoc/fold.html) which are `{{{` and `}}}` (without %'s).  

If this were possible, the folding would be interoperable between VIM and Obsidian.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
Would be added soon.

**Comment by Quorafind** [comment]
Supported.
