### ISSUE TITLE
Feature Request: 增加一个插件设置选项, 点击终止标识符也能触发折叠

### ISSUE THREAD

**Issue by XMB-7** [Quorafind/Obsidian-Fold-Anywhere#7]
### Feature Requested

如题, 有时当折叠主体较长的时候, 点开阅读到结尾后, 想再折叠起来, 此时直接点击位于折叠主体结尾的终止标识符是无效的, 必须往上翻到起始标识符点击, 或者唤出命令面板执行折叠命令才能完成折叠, 操作起来比较繁琐. 
所以希望可以直接点击终止标识符触发折叠操作.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
已支持
